### PR TITLE
Update libraries bom and fix native isssue

### LINKED ISSUE #294: UserError: Classes that should be initialized at run time got initialized during image building - `Slf4jLoggerFactory`
Hi all,

**Description of the issue**
We recently introduced a change in libraries-bom 25.4.0 to [explicitly initialize `Slf4JLoggerFactory` and `Log4JLogger`  at run-time](https://github.com/googleapis/gax-java/blob/0f0996c7c4bea2af3a01979fd3e21cfb6a96d565/gax-grpc/src/main/resources/META-INF/native-image/com.google.api/gax-grpc/native-image.properties#L6) which seems to be resulting in the following error with Quarkus:

```
Step #1: Error: Classes that should be initialized at run time got initialized during image building:
Step #1:  io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory the class was requested to be initialized at run time (from jar:file:///workspace/native-image-samples/native-image-samples-quarkus/quarkus-integration-test/target/quarkus-integration-test-0.14.2-SNAPSHOT-native-image-source-jar/lib/com.google.api.gax-grpc-2.18.1.jar!/META-INF/native-image/com.google.api/gax-grpc/native-image.properties with 'io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory'). To see why io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory got initialized use --trace-class-initialization=io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory
Step #1: 
Step #1: com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
Step #1:  io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory the class was requested to be initialized at run time (from jar:file:///workspace/native-image-samples/native-image-samples-quarkus/quarkus-integration-test/target/quarkus-integration-test-0.14.2-SNAPSHOT-native-image-source-jar/lib/com.google.api.gax-grpc-2.18.1.jar!/META-INF/native-image/com.google.api/gax-grpc/native-image.properties with 'io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory'). To see why io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory got initialized use --trace-class-initialization=io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory
Step #1: 
Step #1: 	at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
Step #1: 	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:555)
Step #1: 	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:168)
Step #1: 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:727)
Step #1: 	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
Step #1: 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:727)
Step #1: 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
Step #1: 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
Step #1: 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:410)
Step #1: 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:594)
Step #1: 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:124)
Step #1: 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:624)
Step #1: [quarkus-integration-test-0.14.2-SNAPSHOT-runner:1884]      [total]:  32,073.30 ms,  3.37 GB
Step #1: # Printing build artifacts to: /workspace/native-image-samples/native-image-samples-quarkus/quarkus-integration-test/target/quarkus-integration-test-0.14.2-SNAPSHOT-native-image-source-jar/quarkus-integration-test-0.14.2-SNAPSHOT-runner.build_artifacts.txt
Step #1: Error: Image build request failed with exit status 1
Step #1: To see how the classes got initialized, use --trace-class-initialization=io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory
```

The reason for the change was to avoid running into this warning: `Warning: class initialization of class io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory failed with exception java.lang.NoClassDefFoundError: Could not initialize class io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.grpc.netty.shaded.io.netty.util.internal.logging.Slf4JLoggerFactory to explicitly request delayed initialization of this class.
` when running native image compilation with services like Pub/Sub. 

**Environment**
JDK:
```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)
```
libraries-bom version: 25.4.0

Reproducer: https://github.com/mpeddada1/simple-quarkus-test

We were wondering if you had experienced this before? We would love to get your insights on how you handle logging your end and any potential solution that could help achieve compatibility? Thank you so much.

cc @meltsufin , @suztomo

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #294

### CODE REVIEW

File: bigquery/deployment/src/main/java/io/quarkiverse/googlecloudservices/bigquery/deployment/BigQueryBuildSteps.java [hunk 1]
```diff
@@ -17,4 +20,12 @@ public FeatureBuildItem feature() {
     public AdditionalBeanBuildItem producer() {
         return new AdditionalBeanBuildItem(BigQueryProducer.class);
     }
+
+    @BuildStep
+    public List<RuntimeInitializedClassBuildItem> runtimeInitializedClass() {
```
Comment (mpeddada1) [inline bigquery/deployment/src/main/java/io/quarkiverse/googlecloudservices/bigquery/deployment/BigQueryBuildSteps.java:25]: Thanks you exploring this further @loicmathieu! Could you be provide more information on the error you received without these configurations? We recently had to add a few configurations for [Apache Arrow in java-bigquery](https://github.com/googleapis/java-bigquery/blob/c5c97b0c6fd98978e3e480cd565bf4f832b35e7c/google-cloud-bigquery/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-bigquery/reflect-config.json#L3) but did not run into an initialization issue so I'm wondering if there a special scenario that we might have missed.
