### PR TITLE
Do not use CDI beans to read the SM

### LINKED ISSUE #491: No longer possible to use secret-manager injected secret in @ConfigMapping class
I have a simple application with the following setup:
```yaml
quarkus:
  google:
    cloud:
      project-id: ${GOOGLE_CLOUD_PROJECT}

# omitted irrelevant configurations

"%secret-manager":
  abc:
    xyz:
      keys:
        - id: some-key-id
          key: ${sm//some-key}
        - id: some-other-key-id
          key: ${sm//some-other-key}
        # etc ...
```

and a following @ConfigMapping interface:
```java
@ConfigMapping(prefix = "abc.xyz")
public interface AbcXyzProperties {

    // other fields ...

    @NotEmpty
    List<Key> keys();

    public interface Key() {
        String id();
        String key();
    }
}
```

Everything was working fine in the version 2.2.0 but since version 2.3.0 application startup ends with the following error:
```
2023-09-02 11:11:23,132 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [secret-manager]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at com.vodeno.dragon.Main.main(Main.java:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.lang.RuntimeException: Error injecting io.quarkiverse.googlecloudservices.common.GcpConfigHolder io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer.gcpConfigHolder
	at io.smallrye.config.ConfigMappingProvider.mapConfigurationInternal(ConfigMappingProvider.java:1003)
	at io.smallrye.config.ConfigMappingProvider.lambda$mapConfiguration$3(ConfigMappingProvider.java:959)
	at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:959)
	at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:91)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:647)
	at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
	at io.quarkus.runtime.generated.Config.createRunTimeConfig(Unknown Source)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
	... 13 more
```

which is a result of
```
  java.util.NoSuchElementException: SRCFG00027: Could not find a mapping for io.quarkiverse.googlecloudservices.common.GcpBootstrapConfiguration
  	at io.smallrye.config.ConfigMappings.getConfigMapping(ConfigMappings.java:111)
  	at io.smallrye.config.SmallRyeConfig.getConfigMapping(SmallRyeConfig.java:412)
  	at io.quarkus.arc.runtime.ConfigMappingCreator.create(ConfigMappingCreator.java:30)
  	at io.quarkiverse.googlecloudservices.common.GcpBootstrapConfiguration_a3a2a72d1f7f6e52c8a965e44841c94f0dd0f329_Synthetic_Bean.createSynthetic(Unknown Source)
  	at io.quarkiverse.googlecloudservices.common.GcpBootstrapConfiguration_a3a2a72d1f7f6e52c8a965e44841c94f0dd0f329_Synthetic_Bean.doCreate(Unknown Source)
  	at io.quarkiverse.googlecloudservices.common.GcpBootstrapConfiguration_a3a2a72d1f7f6e52c8a965e44841c94f0dd0f329_Synthetic_Bean.create(Unknown Source)
  	at io.quarkiverse.googlecloudservices.common.GcpBootstrapConfiguration_a3a2a72d1f7f6e52c8a965e44841c94f0dd0f329_Synthetic_Bean.get(Unknown Source)
  	at io.quarkiverse.googlecloudservices.common.GcpBootstrapConfiguration_a3a2a72d1f7f6e52c8a965e44841c94f0dd0f329_Synthetic_Bean.get(Unknown Source)
  	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:48)
  	at io.quarkiverse.googlecloudservices.common.GcpConfigHolder_Bean.doCreate(Unknown Source)
  	at io.quarkiverse.googlecloudservices.common.GcpConfigHolder_Bean.create(Unknown Source)
  	at io.quarkiverse.googlecloudservices.common.GcpConfigHolder_Bean.create(Unknown Source)
  	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
  	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
  	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
  	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
  	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
  	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
  	at io.quarkiverse.googlecloudservices.common.GcpConfigHolder_Bean.get(Unknown Source)
  	at io.quarkiverse.googlecloudservices.common.GcpConfigHolder_Bean.get(Unknown Source)
  	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_Bean.doCreate(Unknown Source)
  	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_Bean.create(Unknown Source)
  	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_Bean.create(Unknown Source)
  	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
  	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
  	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
  	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
  	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
  	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
  	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_Bean.get(Unknown Source)
  	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_Bean.get(Unknown Source)
  	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.doCreate(Unknown Source)
  	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.create(Unknown Source)
  	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.create(Unknown Source)
  	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
  	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
  	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
  	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
  	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
  	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
  	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.get(Unknown Source)
  	at io.quarkiverse.googlecloudservices.secretmanager.runtime.SecretManagerProducer_ProducerMethod_secretManagerClient_da0d037e46ea741b638dc55997e8c2b5dd43f779_Bean.get(Unknown Source)
  	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:557)
  	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:537)
  	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:570)
  	at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:532)
  	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:279)
  	at io.quarkiverse.googlecloudservices.secretmanager.runtime.config.SecretManagerClientProvider.get(SecretManagerClientProvider.java:18)
  	at io.quarkiverse.googlecloudservices.secretmanager.runtime.config.SecretManagerConfigSource.getValue(SecretManagerConfigSource.java:46)
  	at io.smallrye.config.ConfigValueConfigSourceWrapper.getConfigValue(ConfigValueConfigSourceWrapper.java:20)
         ...
```

It seems like a direct cause of this error was a ConfigPhase change for GcpBootstrapConfiguration.
Do you plan to still support something like described above? Is there any known workaround for my case?

### PR DESCRIPTION
**Pull request by radcortez**
- Fixes #491

### CODE REVIEW

File: secret-manager/runtime/src/main/java/io/quarkiverse/googlecloudservices/secretmanager/runtime/config/SecretManagerConfigSource.java [hunk 1]
```diff
@@ -36,14 +58,43 @@ public Set<String> getPropertyNames() {
...
+            try (FileInputStream is = new FileInputStream(gcpConfig.serviceAccountLocation().get())) {
+                return GoogleCredentials.fromStream(is).createScoped(CLOUD_OAUTH_SCOPE);
+            }
+        } else if (gcpConfig.serviceAccountEncodedKey().isPresent()) {
+            byte[] decode = Base64.getDecoder().decode(gcpConfig.serviceAccountEncodedKey().get());
+            try (ByteArrayInputStream is = new ByteArrayInputStream(decode)) {
+                return GoogleCredentials.fromStream(is).createScoped(CLOUD_OAUTH_SCOPE);
+            }
+        }
+        return GoogleCredentials.getApplicationDefault().createScoped(CLOUD_OAUTH_SCOPE);
```
Comment (loicmathieu) [inline secret-manager/runtime/src/main/java/io/quarkiverse/googlecloudservices/secretmanager/runtime/config/SecretManagerConfigSource.java:98]: This is duplicated with the code in `GcpCredentialProducer.googleCredential()` but as I understand we cannot use a CDI bean here. Maybe the best will be to make the creation of the `GoogleCredentials` from a  `GcpBootstrapConfiguration` in a static method inside `GcpCredentialProducer` so it can be used in both places.

**Review by loicmathieu — CHANGES_REQUESTED** [review]
As I understand it, it will open a second client which scope is linked to the scope of the config object?

**Comment by radcortez** [comment]
> As I understand it, it will open a second client which scope is linked to the scope of the config object?

Correct.

File: secret-manager/runtime/src/main/java/io/quarkiverse/googlecloudservices/secretmanager/runtime/config/SecretManagerConfigSource.java (hunk 1 above)
Comment (radcortez) [reply secret-manager/runtime/src/main/java/io/quarkiverse/googlecloudservices/secretmanager/runtime/config/SecretManagerConfigSource.java:98]: Yes, I've considered that option.

The issue is that `GcpCredentialProducer.googleCredential()` has additional CDI dependencies, namely token authentication, which uses the OIDC extension (if available):

https://github.com/quarkiverse/quarkus-google-cloud-services/blob/38a890522af6cd08410cad08f11064030a27a595/common/runtime/src/main/java/io/quarkiverse/googlecloudservices/common/GcpCredentialProducer.java#L41-L67

I had to remove that piece for the ConfigSource part, because we cannot support it.

Comment (loicmathieu) [reply secret-manager/runtime/src/main/java/io/quarkiverse/googlecloudservices/secretmanager/runtime/config/SecretManagerConfigSource.java:98]: Oh yes, I read the code too quickly.
OK then, I'll rebease on main to have a fresh CI build and if everything is green I'll merge it.
Thanks
